### ISSUE TITLE
Cover data tool component by autotests

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-ui-tests#16]
see check-list 
http://jmix-testit.haulmont.com/projects/5/tests?isolatedSection=68cb69b7-7f57-452b-971f-ef5ec23107ef

**Comment by owlet1997** [comment]
Covered cases:
- delete instance from Entity Inspector Browser
- wipe out instance from Entity Inspector Browser
- restore deleted instance from Entity Inspector Browser
- show modes selecting in Entity Inspector Browser
- Entity information window invoking from deleted and non-deleted instance in Entity Inspector Browser
- copying DDL scripts from Entity information window

**Comment by owlet1997** [comment]
Covered cases:
- create/edit simple entity
- create/edit entity with enum
- create/edit entity with Composition One to One
- create/edit entity with Composition One to Many

**Comment by owlet1997** [comment]
Covered cases:
- create/edit entity with Assotiation Many to Many
- export entity in JSON/ZIP formats
