### ISSUE TITLE
Cover reporting component by autotests

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-ui-tests#24]
see http://jmix-testit.haulmont.com/projects/5/tests?isolatedSection=dc2e9592-a35c-4d83-a798-21af860c5722

**Comment by owlet1997** [comment]
# Checked cases:
## creating reports
- [ ] from one entity
- [ ] from list of entities
- [ ] from list of entities, selected by query
- [ ] by copying existed report
- [ ] table type report
- [ ] serial chart type report
- [ ] pie chart type report
## running reports
- [ ] from region window
- [ ] from JPQL query window
- [ ] from editor
- [ ] from report browser
- [ ] from run report screen
## adding report regions
- [ ] simple region
- [ ] tabulated region
- [ ] reordering attributes in a simple region
- [ ] reordering attributes in a tabulated region
## group editing
- [ ] create group
- [ ] edit group
- [ ] remove non-system group without reports
- [ ] remove system group
- [ ] add report to existing group
- [ ] remove group with reports
## report browser buttons
- [ ] export report
- [ ] remove report
- [ ] open execution history screen
## report editing
- [ ] create parameters with simple types
- [ ] create parameters with enum, entity, list of entities types
- [ ] edit parameter
- [ ] remove parameter
- [ ] create format value
- [ ] edit format value
- [ ] remove format value
- [ ] select role for report
- [ ] select screen for report
