### ISSUE TITLE
Cover TextField in sampler project by autotests

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-ui-tests#5]
1. Simple textField
-check input value for field without maxLength
-check input value for field with maxLength
2. Data-aware textField
-check predefined value in field
-change value of field
3. TextField with datatype
-input correct/incorrect type of value to fields
4. TextField with validator
-input correct/incorrect value to field with positive validator
-input correct/incorrect value to field with border value validator
5. TextField  with trim attribute
-check value with spase in the end while trim is on/off
-check string containing spaces only while trim is on/off
6. TextField  with EnterPress listener
-set value and press enter
7. TextField with TextChange listener
-check changing value of field
8. TextField with TextChange EventMode
-check TextChangeEventMode with EAGER value
-check TextChangeEventMode with LAZY value
-check TextChangeEventMode with BLUR value
-check TextChangeEventMode with TIMEOUT value
9. MaskedField
-check output for valueMode=masked
-check output for valueMode=clear
10. PaswordField
-check ability to hide password and view value using passwordField.getValue()

works correctly with https://github.com/Haulmont/jmix-sampler/tree/maistrenko

**Comment by natfirst** [comment]
In DatatypeTextFieldUiTest change type of INTEGER_VALUE and DOUBLE_VALUE variables to String and do not use type conversion in `setValue` method.
